export const MEAL_TYPES = ["Breakfast", "Lunch", "Dinner"];

export const HALLS_OF_RESIDENCE = [
  "Winslow",
  "Emerald",
  "Topaz",
  "Adeniji Adeleke",
  "Welch",
  "Nelson Mandela",
  "Gideon Troopers",
  "Samuel Akande",
  "Bethel Splendor",
  "Felicia Adebisi Dada",
  "Queen Esther",
  "Platinum",
  "Ameyo Adadevoh",
  "Justice Deborah",
  "Neal Wilson",
  "Havilah Gold",
  "Crystal",
  "Gamaliel",
  "White",
  "Nybergr",
  "Diamond",
  "Ogden",
  "Iperu",
].sort((a, b) => (a > b ? 1 : -1));
